version: "3"

services:
  bot:
    container_name: task_manager_bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: on-failure
    depends_on:
      - db
      - app
    networks:
      - network_service

  app:
    container_name: task_manager_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
    restart: on-failure
    volumes:
      - app:/usr/src/app/
    depends_on:
      - db
    networks:
      - network_service
    expose:
      - ${APP_PORT}

  db:
    image: postgres:14
    container_name: task_manager_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: on-failure
    volumes:
      - psql:/var/lib/postgresql/data
    networks:
      - network_service
    expose:
      - ${DB_PORT}

volumes:
  app:
  psql:

networks:
  network_service:
    driver: bridge
